### PR TITLE
react: Fix build with next/webpack + react@<18.0.0

### LINKED ISSUE #782: [bug] React component failed to build with Next.js 12
@giscus

## What happened?

When I update `giscus-react` from `2.2.2` to `2.2.3`, Next.js 12 building crashed with an error:

```text
info  - Collecting page data .Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Work\Community\KaiYuanShe\OWS\node_modules\.pnpm\@giscus+react@2.2.3_sfoxds7t5ydpegc3knd667wn6m\node_modules\react\jsx-runtime' imported from D:\Work\Community\KaiYuanShe\OWS\node_modules\.pnpm\@giscus+react@2.2.3_sfoxds7t5ydpegc3knd667wn6m\node_modules\@giscus\react\dist\index.mjs    
Did you mean to import react@17.0.2/node_modules/react/jsx-runtime.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

> Build error occurred
Error: Failed to collect page data for /article/[id]
    at D:\Work\Community\KaiYuanShe\OWS\node_modules\.pnpm\next@12.3.3_sfoxds7t5ydpegc3knd667wn6m\node_modules\next\dist\build\utils.js:916:15 {
  type: 'Error'
}
```

## Environment

| Software         | Version(s)          |
| ---------------- | ------------------- |
| React            | 17.0.2              |
| Next.js          | 12.3.3              |
| Node             | 16.18.0             |
| PNPM             | 7.15.0              |
| Operating System | Windows 10 Pro 21H2 |

### PR DESCRIPTION
**Pull request by strickczq**
build only cjs to be compatible with `react@<18.0.0`, and use a wrapper to support esm.

## About this PR

This is going to fix #782 .

## What's the problem

In `@giscus/react@2.2.2`, next/webpack will resolve `@giscus/react` to only `./dist/index.cjs.js` whatever you write `require` or `import` in your project, which escapes the issue.

(`console.log` was added manually for debugging)
image

But in `@giscus/react@2.2.3`, with `.mjs` extension for esm `import` configured, `@giscus/react` will be resolved to `./dist/index.cjs` when using `require`, and `./dist/index.mjs` when using `import`.

`./dist/index.mjs`  imports `react/jsx-runtime`which triggers this issue from react https://github.com/facebook/react/issues/20235 .

image

## The workaround

To be compatible with `react@<18.0.0`, we should only `require` the `react/jsx-runtime` (no esm `import`) in our build products.

To be esm compatible, we can use a wrapper mjs that imports the cjs product. Official approach here https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper

So I wrote a vite plugin to emit the wrapper file.

(`console.log` was added manually for debugging)
image

Thus, everything works fine!

## My testing environment

node: 16.18.1
npm: 8.19.2
next: 12.3.3
react: 17.0.2

### CODE REVIEW

**Comment by laymonage** [comment]
Thank you very much for the excellent, in-depth writeup and fix! I don't think I could figure this out on my own 😆
